# Generated by Django 5.1.7 on 2025-03-13 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=150, verbose_name='тема письма')),
                ('body', models.TextField(verbose_name='тело письма')),
            ],
            options={
                'verbose_name': 'управление сообщением',
                'verbose_name_plural': 'управление сообщениями',
                'ordering': ['topic'],
            },
        ),
        migrations.CreateModel(
            name='EmailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=150, verbose_name='ф.и.о')),
                ('comment', models.TextField(verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'получатель расслылки',
                'verbose_name_plural': 'получатели рассылок',
                'ordering': ['email', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='Sending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_start', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время начало отправки')),
                ('datetime_end', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время окончания отправки')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('started', 'Запущена'), ('ended', 'Завершена')], default='created', max_length=18, verbose_name='статус рассылки')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_sending.emailmanagement', verbose_name='Сообщения')),
                ('recipients', models.ManyToManyField(to='email_sending.emailrecipient', verbose_name='получатели')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
                'ordering': ['message'],
            },
        ),
        migrations.CreateModel(
            name='EmailingTry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время попытки')),
                ('status', models.CharField(choices=[('successful', 'успешно'), ('failed', 'не успешно')], max_length=18, verbose_name='статус рассылки')),
                ('email_answer', models.TextField(blank=True, null=True, verbose_name='Ответ почтового сераера')),
                ('sending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_sending.sending', verbose_name='попытка рассылки')),
            ],
            options={
                'verbose_name': 'попытка рассылки',
                'verbose_name_plural': 'попытка рассылок',
                'ordering': ['-datetime'],
            },
        ),
    ]
