# Generated by Django 5.1.7 on 2025-03-26 13:29

import django.db.models.deletion
import django.template.defaulttags
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_sending", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Успешно"), ("failed", "Неуспешно")],
                        max_length=10,
                    ),
                ),
                ("response", models.TextField(blank=True, null=True)),
                (
                    "timestamp",
                    models.DateTimeField(default=django.template.defaulttags.now),
                ),
                (
                    "email_management",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="email_sending.emailmanagement",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="email_sending.emailrecipient",
                    ),
                ),
            ],
        ),
    ]
