# Generated by Django 5.1.7 on 2025-04-03 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_sending", "0002_mailingattempt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sending",
            options={
                "ordering": ["message"],
                "permissions": [
                    ("can_unpublish_sending", "Can unpublish sending"),
                    ("can_delete_sending", "Can delete sending"),
                    ("view_all_sending", "View all sendings"),
                ],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
        migrations.AddField(
            model_name="sending",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
